services:
  - type: web
    name: truesmart-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: Server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        fromConfigVar: MONGO_URI
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://truesmart.vercel.app/
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

